name: Ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: docker image build
      uses: docker/login-action@v3
      with: 
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
    - name: Docker push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: arunagri03/ng:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: deploy to ec2
      run: |
        chmod 600 /path/to/private-key.pem
        ssh -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} "docker pull arunagri03/ng:${{ github.run_id }} && docker run -d -p 80:80 arunagri03/ng:${{ github.run_id }}"
